services:
  - type: web
    name: discord-dice-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: ./start.sh
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false