services:
  - type: web
    name: discord-bot
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false